[tool.poetry]
name = "projeto_1"
version = "0.1.0"
description = ""
authors = ["Sávio Rodrigues <srodrigues@wake.tech>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pyspark = "^3.5.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
